version: "3.9"

services:

# Go application service
  go-app:
    build:
      context: go/.
      args:
        - GO111MODULE=on
    #ports:
    #  - "8080:8080"
    environment:
      - VIRTUAL_HOST=ip.brothertec.eu
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=ip.brothertec.eu
      - LETSENCRYPT_EMAIL=admin@brothertec.eu

    #volumes: 
    #  - ./uploads:/uploads

    restart: always

    labels:
      - flame.type=application
      - flame.name=Get IP
      - flame.url=https://ip.brothertec.eu/getip
      - flame.icon=ip

    networks:
      default:
      proxy:
      edge-tier:

networks:
  proxy:
    name: nginx-proxy
    external: true
  edge-tier:
    name: edge
    external: true
